title: CS184 HW Writeup Webpages
description: CS184 Computer Graphics and Imaging - Homework Documentation and Results
theme: just-the-docs

url: https://buqiliao.github.io
baseurl: "/CS184-HW"

plugins:
  - jekyll-remote-theme

head_scripts:
  - /assets/css/custom.css

aux_links:
  CS184 Course: https://cs184.eecs.berkeley.edu/
  Course Materials: https://cs184.eecs.berkeley.edu/sp24
